# Generated by Django 5.0.6 on 2024-05-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UserSignIn", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
